# basic go docker compose
version: "3.9"
services:
  memory:
    container_name: memory_api
    build: .
    ports: ["8080:8080"]
    volumes:
    - ./:/go/src/app
    depends_on: 
    - db
  db:
    container_name: postgres_db
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
